### PR TITLE
Flexible routes

### PR DESCRIPTION
**Pull request by lsetiawan**
## Overview

This PR modifies xpublish to be able to server multiple datasets based on @benbovy [prototype](https://gist.github.com/benbovy/f687e1697e18e39e4924872cd83a60e9).

This is an attempt to address #23 and #25.

## Notes

Further analysis needs to be done to see if dask is working correctly and also caching, otherwise, it seems to work to serve multiple datasets.

### CODE REVIEW

**Comment by lsetiawan** [comment]
Update: Looks like caching is broken and `RestAccessor` needs values from `DatasetAccessor` to pass tests, needs further work to get the logic to work better...

**Comment by lsetiawan** [comment]
Closing this for now. Seems like this logic deviates too much from the rest accessor..

**Comment by benbovy** [comment]
Thanks for giving it a try @lsetiawan.

A few comments:

- `RestAccessor` is registered as a [xarray dataset accessor](http://xarray.pydata.org/en/stable/internals.html#extending-xarray), so it should still be used for serving one dataset object only. For the case of multiple datasets, I suggest to put the logic in another class (e.g., a better name than `RestCollection`) that is not registered as a xarray dataset accessor but that provides a similar interface, i.e., a `.app` property and a `.serve()` method.

- You have moved the zarr logic into a separate class `utils.DatasetAccessor`, which I think is a good approach (this zarr layer can be decoupled from the rest layer). Registering it as another dataset accessor for internal use (e.g., `Dataset._zutils.<methods>`) would be slightly cleaner, IMO, so that elsewhere in the code we could stick with `xarray.Dataset` objects.

- CI fails because some tests want to access some attributes which have moved from `RestAccessor` to `utils.DatasetAccessor`.

I have a pretty clear idea in mind on how to implement this, so if you don't mind I'll try to see if I can submit a PR soon. Probably best will be to split the work into multiple PRs, as it requires some heavy refactoring. Also, it would be better tackling one problem at a time, i.e., (1) refactor existing routes using a `APIRouter` wrapper, (2) allow overriding default routers and/or plugging in custom routers in `RestAccessor`, (3) implement serving multiple datasets.

**Comment by benbovy** [comment]
@jhamman any work on this will likely conflict with #21. Should we merge it first or is it still wip?

**Comment by lsetiawan** [comment]
@benbovy Go ahead and make your PR, I thought I was able to implement it that way, but I think I'll need to see what you got and I can expand on that. :smile: Thanks!

**Pull request closed without merging**
